import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Banner from "@/components/homepage/Banner";
import Footer from "@/components/shared/Footer";
import CardProvider from "@/context/CardContext";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Assignment-06",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{children:React.ReactNode}>) {
  return (
    <html
    data-theme="dark"
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
       <CardProvider>
        <Navbar/> 
        <main>
          {children}
        </main>
        <Footer/>
        <ToastContainer />
        </CardProvider>
        </body>
    </html>
  );
}
